/* Form definition file generated by fdesign on Wed Jun  6 18:01:46 2018 */

#include <stdlib.h>
#include "xfirewall.h"

#include "folder.xpm"

/***************************************
 ***************************************/

FD_xfirewall *
create_form_xfirewall( void )
{
    FL_OBJECT *obj;
    FD_xfirewall *fdui = ( FD_xfirewall * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->xfirewall = fl_bgn_form( FL_NO_BOX, 1022, 561 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 1022, 561, "" );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->outbound_tcp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 40, 30, 180, 20, "Limit Outbound TCP Ports" );
    fl_set_object_callback( obj, outbound_tcp_cb, 0 );

    fdui->outbound_udp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 40, 100, 180, 20, "Limit Outbound UDP Ports" );
    fl_set_object_callback( obj, outbound_udp_cb, 0 );

    fdui->outbound_tcp_list = obj = fl_add_input( FL_NORMAL_INPUT, 50, 60, 310, 30, "" );
    fl_set_object_callback( obj, outbound_tcp_list_cb, 0 );

    fdui->outbound_udp_list = obj = fl_add_input( FL_NORMAL_INPUT, 50, 130, 310, 30, "" );
    fl_set_object_callback( obj, outbound_udp_list_cb, 0 );

    fdui->inbound_tcp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 40, 170, 180, 20, "Allow Inbound TCP" );
    fl_set_object_callback( obj, inbound_tcp_cb, 0 );

    fdui->inbound_tcp_list = obj = fl_add_input( FL_NORMAL_INPUT, 50, 200, 310, 30, "" );
    fl_set_object_callback( obj, inbound_tcp_list_cb, 0 );

    fdui->inbound_udp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 40, 250, 180, 20, "Allow Inbound UDP" );
    fl_set_object_callback( obj, inbound_udp_cb, 0 );

    fdui->inbound_udp_list = obj = fl_add_input( FL_NORMAL_INPUT, 50, 280, 310, 30, "" );
    fl_set_object_callback( obj, inbound_udp_list_cb, 0 );

    fdui->autotrust = obj = fl_add_button( FL_NORMAL_BUTTON, 50, 500, 130, 40, "Autotrust" );
    fl_set_object_callback( obj, autotrust_cb, 0 );

    fdui->default_rules = obj = fl_add_button( FL_NORMAL_BUTTON, 200, 500, 130, 40, "Default" );
    fl_set_object_callback( obj, default_rules_cb, 0 );

    fdui->allow_all = obj = fl_add_button( FL_NORMAL_BUTTON, 350, 500, 130, 40, "Allow All" );
    fl_set_object_callback( obj, allow_all_cb, 0 );

    fdui->deny_all = obj = fl_add_button( FL_NORMAL_BUTTON, 500, 500, 130, 40, "Deny All" );
    fl_set_object_callback( obj, deny_all_cb, 0 );

    fdui->cancel = obj = fl_add_button( FL_NORMAL_BUTTON, 700, 500, 130, 40, "Cancel" );
    fl_set_object_callback( obj, cancel_cb, 0 );

    fdui->accept = obj = fl_add_button( FL_NORMAL_BUTTON, 850, 500, 130, 40, "Accept" );
    fl_set_object_callback( obj, accept_cb, 0 );

    fdui->outbound_hosts = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 410, 30, 240, 20, "Limit Outbound Hosts" );
    fl_set_object_callback( obj, outbound_hosts_cb, 0 );

    fdui->outbound_load_file = obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 50, 150, 30, "Load from File" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, outbound_load_file_cb, 0 );

    fdui->outbound_enter_manually = obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 90, 150, 30, "Enter Manually" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, outbound_enter_manually_cb, 0 );

    fdui->inbound_hosts = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 410, 170, 240, 20, "Allow Inbound Hosts" );
    fl_set_object_callback( obj, inbound_hosts_cb, 0 );

    fdui->inboud_load_file = obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 200, 150, 30, "Load from File" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, inboud_load_file_cb, 0 );

    obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 240, 150, 30, "Enter Manually" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, outbound_enter_manually_cb, 0 );

    fdui->deny_hosts = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 410, 320, 240, 20, "Deny hosts regardless" );
    fl_set_object_callback( obj, deny_hosts_cb, 0 );

    fdui->deny_load_file = obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 350, 150, 30, "Load from File" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, deny_load_file_cb, 0 );

    obj = fl_add_lightbutton( FL_PUSH_BUTTON, 420, 390, 150, 30, "Enter Manually" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, deny_enter_manually_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 420, 130, 118, 30, "Hosts loaded:" );

    fdui->outbound_hosts_count = obj = fl_add_box( FL_UP_BOX, 527, 130, 43, 30, "0" );

    obj = fl_add_text( FL_NORMAL_TEXT, 420, 280, 118, 30, "Hosts loaded:" );

    fdui->inbound_hosts_count = obj = fl_add_box( FL_UP_BOX, 527, 280, 43, 30, "0" );

    obj = fl_add_text( FL_NORMAL_TEXT, 420, 430, 118, 30, "Hosts loaded:" );

    fdui->deny_hosts_count = obj = fl_add_box( FL_UP_BOX, 527, 430, 43, 30, "0" );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 630, 50, 350, 150, "Behaviors" );

    fdui->send_resets = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 70, 310, 20, "Send resets instead of dropping packets" );
    fl_set_object_callback( obj, send_resets_cb, 0 );

    fdui->dont_restrict_icmp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 100, 310, 20, "Don't restrict ICMP to only Echo/Reply" );
    fl_set_object_callback( obj, dont_restrict_icmp_cb, 0 );

    fdui->dont_allow_dhcp = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 130, 310, 20, "Don't Allow DHCP" );
    fl_set_object_callback( obj, dont_allow_dhcp_cb, 0 );

    fdui->log_exceptions = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 160, 310, 20, "Log Exceptions" );
    fl_set_object_callback( obj, log_exceptions_cb, 0 );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 630, 210, 350, 120, "Options" );

    fdui->simulate_only = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 230, 310, 20, "Simulate setting firewall" );
    fl_set_object_callback( obj, simulate_only_cb, 0 );

    fdui->show_status = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 260, 310, 20, "Show status messages" );
    fl_set_object_callback( obj, show_status_cb, 0 );

    fdui->show_rules = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 650, 290, 310, 20, "Show rules after they are set" );
    fl_set_object_callback( obj, show_rules_cb, 0 );

    fdui->save_script = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 630, 360, 350, 30, "Instead of setting rules, generate and save script" );
    fl_set_object_callback( obj, save_script_cb, 0 );

    fdui->save_file_name = obj = fl_add_input( FL_NORMAL_INPUT, 680, 390, 290, 30, "" );

    fdui->save_file_picker = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 640, 390, 40, 30, "" );
    fl_set_object_callback( obj, save_file_picker_cb, 0 );
    fl_set_pixmapbutton_data( obj, folder2 );

    fl_end_form( );

    fdui->xfirewall->fdui = fdui;

    return fdui;
}
