/* Header file generated by fdesign on Wed Jun  6 17:16:54 2018 */

#ifndef FD_xfirewall_h_
#define FD_xfirewall_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

void outbound_tcp_cb( FL_OBJECT *, long );
void outbound_udp_cb( FL_OBJECT *, long );
void outbound_tcp_list_cb( FL_OBJECT *, long );
void outbound_udp_list_cb( FL_OBJECT *, long );
void inbound_tcp_cb( FL_OBJECT *, long );
void inbound_tcp_list_cb( FL_OBJECT *, long );
void inbound_udp_cb( FL_OBJECT *, long );
void inbound_udp_list_cb( FL_OBJECT *, long );
void autotrust_cb( FL_OBJECT *, long );
void default_rules_cb( FL_OBJECT *, long );
void allow_all_cb( FL_OBJECT *, long );
void deny_all_cb( FL_OBJECT *, long );
void cancel_cb( FL_OBJECT *, long );
void accept_cb( FL_OBJECT *, long );
void outbound_hosts_cb( FL_OBJECT *, long );
void outbound_load_file_cb( FL_OBJECT *, long );
void outbound_enter_manually_cb( FL_OBJECT *, long );
void inbound_hosts_cb( FL_OBJECT *, long );
void inboud_load_file_cb( FL_OBJECT *, long );
void deny_hosts_cb( FL_OBJECT *, long );
void deny_load_file_cb( FL_OBJECT *, long );
void deny_enter_manually_cb( FL_OBJECT *, long );
void send_resets_cb( FL_OBJECT *, long );
void dont_restrict_icmp_cb( FL_OBJECT *, long );
void dont_allow_dhcp_cb( FL_OBJECT *, long );
void log_exceptions_cb( FL_OBJECT *, long );
void simulate_only_cb( FL_OBJECT *, long );
void show_status_cb( FL_OBJECT *, long );
void show_rules_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * xfirewall;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * outbound_tcp;
    FL_OBJECT * outbound_udp;
    FL_OBJECT * outbound_tcp_list;
    FL_OBJECT * outbound_udp_list;
    FL_OBJECT * inbound_tcp;
    FL_OBJECT * inbound_tcp_list;
    FL_OBJECT * inbound_udp;
    FL_OBJECT * inbound_udp_list;
    FL_OBJECT * autotrust;
    FL_OBJECT * default_rules;
    FL_OBJECT * allow_all;
    FL_OBJECT * deny_all;
    FL_OBJECT * cancel;
    FL_OBJECT * accept;
    FL_OBJECT * outbound_hosts;
    FL_OBJECT * outbound_load_file;
    FL_OBJECT * outbound_enter_manually;
    FL_OBJECT * inbound_hosts;
    FL_OBJECT * inboud_load_file;
    FL_OBJECT * deny_hosts;
    FL_OBJECT * deny_load_file;
    FL_OBJECT * outbound_hosts_count;
    FL_OBJECT * inbound_hosts_count;
    FL_OBJECT * deny_hosts_count;
    FL_OBJECT * send_resets;
    FL_OBJECT * dont_restrict_icmp;
    FL_OBJECT * dont_allow_dhcp;
    FL_OBJECT * log_exceptions;
    FL_OBJECT * simulate_only;
    FL_OBJECT * show_status;
    FL_OBJECT * show_rules;
} FD_xfirewall;

FD_xfirewall * create_form_xfirewall( void );

#endif /* FD_xfirewall_h_ */
